feign:
  client:
    url:
      login: https://ip-manager-service-test.puertocartagena.com:3706/auth
      ipManager: https://ip-manager-service-test.puertocartagena.com:3706/ip_master

spring:
  thymeleaf:
    enabled: false

# Configuración Recapchat
google:
  recaptcha:
    siteKey: 6Ldcr5goAAAAAHXe6ZrDKReJojcqZ0ZBjfL3a6bL
    secret: 6Ldcr5goAAAAANYYMoKqjgWbASymh7m1zG6X1MUS
    enabled: false
    score: 0.5
    endpoint: https://www.google.com/recaptcha/api/siteverify