feign:
  client:
    url:
      login: https://ip-manager-service-test.puertocartagena.com:3706/auth
      ipManager: https://ip-manager-service-test.puertocartagena.com:3706/ip_master

spring:
  thymeleaf:
    enabled: false

server:
  port: 8080

# Configuración Recapchat
google:
  recaptcha:
    siteKey: 6LdudvIoAAAAADmTXgpAvR_7B_ehUayfxmM7_kA1
    secret: 6LdudvIoAAAAAKvtdOR9F8g2A0Dm4AFKjInVGOmp
    enabled: false
    score: 0.5
    endpoint: https://www.google.com/recaptcha/api/siteverify