feign:
 client:
   url:
     login: http://localhost:3706/auth
     ipManager: http://localhost:3706/ip_master

spring:
  thymeleaf:
    enabled: false

# Configuración Recapchat
google:
  recaptcha:
    secret: 6LdIkk8oAAAAAP_GUlvqyA0ra_Xo93d9GPuiexu6
    enabled: false
    score: 0.5